[workspace]
members = ["projects/*"]
default-members = [
    "projects/primes-web",
]
exclude = [
    "projects/.DS_Store",
    "projects/primes-linear",
]

[profile.release]
lto = true
panic = "abort"
